{
 "title": "rpki-client CA repository",
 "description": "rpki-client overview",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Host:",
    "query": {
     "query": "label_values(rpki_client_info,nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(rpki_client_info{nodename=\"$name\"}, instance)"
    }
   },
   {
    "name": "tal",
    "label": "TAL",
    "query": {
     "query": "label_values(rpki_client_ta_objects{instance=\"$instance\"},name)"
    }
   },
   {
    "name": "carepo",
    "label": "CA Repo",
    "query": {
     "query": "label_values(rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\"},carepo)"
    }
   },
   {
    "name": "notify",
    "label": "Notify URI",
    "query": {
     "query": "label_values(rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\"},notify)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Completion",
   "type": "stat",
   "description": "Job completion time",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_job_completion_time{instance=\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique VRP",
   "type": "stat",
   "description": "Unique Validated ROA payloads",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"vrp\", state=\"unique\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique VAP",
   "type": "stat",
   "description": "Unique Validated ASPA payloads",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"vap\", state=\"unique\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Router Keys",
   "type": "stat",
   "description": "BGPsec router certificates",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"router_key\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Object Churn",
   "type": "timeseries",
   "description": "New or Deleted files in a CARepository",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (state) (rpki_client_repository_objects{instance=\"$instance\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"files\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Repository Sync Time",
   "type": "timeseries",
   "description": "Time to synchronize repository",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "rpki_client_repository_duration{instance=\"$instance\", carepo=~\"$carepo\", notify=~\"$notify\"}",
     "legendFormat": "{{carepo}}"
    }
   ]
  },
  {
   "title": "Sync time",
   "type": "gauge",
   "description": "Last repository sync time",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_repository_duration{carepo=~\"$carepo\", notify=~\"$notify\"})"
    }
   ]
  },
  {
   "title": "Total Certificates",
   "type": "stat",
   "description": "Total Validated Certificates",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"cert\", state=\"valid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Manifests",
   "type": "stat",
   "description": "Total Validated Manifests",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"manifest\", state=\"valid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Payloads",
   "type": "stat",
   "description": "Total Validated ROA, ASPA, GBR and other payloads",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type!~\"cert|crl|manifest\", state=\"valid\"})",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  { "title": "Validated Objects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Validated ROA payloads",
   "type": "timeseries",
   "description": "Validated ROA payloads",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"vrp\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Validated ASPA payloads",
   "type": "timeseries",
   "description": "Validated ASPA payloads",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"vap\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Validated Router Keys",
   "type": "timeseries",
   "description": "Validated Router Keys",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(state) (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type=\"router_key\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Object information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Valid Objects",
   "type": "timeseries",
   "description": "Valid Objects",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type) (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", state=\"valid\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Excluded Objects",
   "type": "timeseries",
   "description": "Excluded Objects",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (type, state) (rpki_client_repository_objects{instance=\"$instance\", name=~\"$tal\", carepo=~\"$carepo\", notify=~\"$notify\", type!~\"v[ar]p.*\", state!=\"valid\"})",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  }
 ]
}