{
 "title": "RPKI Changes",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(rpki_client_repository,instance)"
    }
   },
   {
    "name": "tal",
    "label": "TAL",
    "query": {
     "query": "label_values(rpki_client_ta_objects,name)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "15m,20m,30m" }
  ]
 },
 "panels": [
  {
   "title": "vrp count changes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (instance,type) (rpki_client_objects{state=\"unique\",type=\"vrp\",instance=~\"$instance\"} - rpki_client_objects{state=\"unique\",type=\"vrp\",instance=~\"$instance\"} offset $interval)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "carepo count changes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "max by (carepo) (rpki_client_repository_objects{state=\"unique\",type=\"vrp\",name=~\"$tal\",instance=~\"$instance\"} - rpki_client_repository_objects{state=\"unique\",type=\"vrp\",name=~\"$tal\",instance=~\"$instance\"} offset $interval)",
     "legendFormat": "{{carepo}}"
    }
   ]
  },
  {
   "title": "Biggest additions",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max by (carepo) (rpki_client_repository_objects{state=\"unique\",type=\"vrp\",name=~\"$tal\",instance=~\"$instance\"} - rpki_client_repository_objects{state=\"unique\",type=\"vrp\",name=~\"$tal\",instance=~\"$instance\"} offset $interval) > 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Biggest removals",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "max by (carepo) (rpki_client_repository_objects{state=\"unique\",type=\"vrp\",name=~\"$tal\",instance=~\"$instance\"} - rpki_client_repository_objects{state=\"unique\",type=\"vrp\",name=~\"$tal\",instance=~\"$instance\"} offset $interval) < -100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}