{
 "title": "rpki-client Global overview",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Unique VRPs per instance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance) (rpki_client_objects{type=~\"vrp\", state=\"unique\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (rpki_client_duration{type=\"elapsed\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Non-functional CAs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) (rpki_client_repository_objects{type=\"cert\", state=\"non-functional\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (instance) (rpki_client_repository_objects{type=\"files\", state=\"new\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Extra files",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (instance) (rpki_client_repository_objects{type=\"files\", state=\"extra\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}