{
 "title": "rpki-client overview",
 "description": "rpki-client overview",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(rpki_client_repository,instance)"
    }
   },
   {
    "name": "tal",
    "label": "TAL",
    "query": {
     "query": "label_values(rpki_client_ta_objects,name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Completion",
   "type": "stat",
   "description": "Job completion time",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_job_completion_time{instance=~\"$instance\"} * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unique VRP",
   "type": "stat",
   "description": "Unique Validated ROA payloads",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_objects{instance=~\"$instance\", type=~\"vrp\", state=\"unique\"}",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  {
   "title": "Unique VAP",
   "type": "stat",
   "description": "Unique Validated ASPA payloads",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_objects{instance=~\"$instance\", type=~\"vap\", state=\"unique\"}",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  {
   "title": "Router Keys",
   "type": "stat",
   "description": "BGPsec router certificates",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_objects{instance=~\"$instance\", type=\"router_key\"}",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  {
   "title": "Run Time",
   "type": "timeseries",
   "description": "rpki-client runtime (elapsed, user and system)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "expr": "rpki_client_duration{instance=~\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Last Run time",
   "type": "gauge",
   "description": "Elapsed time of last run",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_duration{instance=~\"$instance\", type=\"elapsed\"}"
    }
   ]
  },
  {
   "title": "Total Certificates",
   "type": "stat",
   "description": "Total Validated Certificates",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_objects{instance=~\"$instance\", type=\"cert\", state=\"valid\"}",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  {
   "title": "Total Manifests",
   "type": "stat",
   "description": "Total Validated Manifests",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpki_client_objects{instance=~\"$instance\", type=~\"manifest\", state=\"valid\"}",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  {
   "title": "Total Objects",
   "type": "stat",
   "description": "Total Validated ROA, ASPA, and other objects.\nExcluding certificates, manifests and CRLs.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rpki_client_objects{instance=~\"$instance\", type!~\"cert|crl|manifest\", state=\"valid\"})",
     "legendFormat": "{{type}} {{state}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "rpki-client version",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rpki_client_info{instance=~\"$instance\"}",
     "legendFormat": "{{release}}"
    }
   ]
  },
  {
   "title": "File churn overview",
   "type": "timeseries",
   "description": "Superfluous \"extra\" files in RRDP, number new of files moved into validated cache, number of files deleted",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum by (state) (rpki_client_repository_objects{instance=~\"$instance\", type=\"files\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRPs per TAL",
   "type": "timeseries",
   "description": "Validated ROA Payloads split by TAL",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rpki_client_ta_objects{instance=~\"$instance\", type=\"vrp\", state=\"total\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Repositories",
   "type": "timeseries",
   "description": "Status of RPKI repositories",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (rpki_client_repository{instance=~\"$instance\", state=~\"synced\"})",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum by (state) (rpki_client_repository{instance=~\"$instance\", state=~\"failed\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "$tal - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }, "repeat": "tal" },
  {
   "title": "$tal - valid Objects",
   "type": "timeseries",
   "description": "Valid objects found under $tal TAL",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rpki_client_ta_objects{instance=~\"$instance\", name=~\"$tal\", state=\"valid\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "$tal - Excluded Objects",
   "type": "timeseries",
   "description": "Invalid objects found under $tal TAL",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (state) (rpki_client_ta_objects{instance=~\"$instance\", name=~\"$tal\", type!~\"v[ar]p.*\", state!=\"valid\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$tal - validated ROA payloads",
   "type": "timeseries",
   "description": "Validated ROA payloads covered by $tal TAL",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rpki_client_ta_objects{instance=~\"$instance\", type=\"vrp\", name=~\"$tal\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "$tal - validated ASPA payloads",
   "type": "timeseries",
   "description": "Validated ASPA payloads covered by $tal TAL",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rpki_client_ta_objects{instance=~\"$instance\", type=\"vap\", name=~\"$tal\"}",
     "legendFormat": "{{state}}"
    }
   ]
  }
 ]
}